services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: local
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - py_challange:/data

  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=local
      - MINIO_SECRET_KEY=admin123
    depends_on:
      - minio
    volumes:
      - py_challange:/data

  data-service:
    build:
      context: ./data-service
    ports:
      - "8777:8777"

  frontend:
    build:
      context: ./fronted
    container_name: streamlit-fronted
    ports:
      - "8501:8501"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=local
      - MINIO_SECRET_KEY=admin123
    depends_on:
      - backend
      - data-service
      - minio
    volumes:
      - py_challange:/data

volumes:
  py_challange:
